#
# Copyright (c) 2023 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# This TOML configuration adds configurations for UICR that are currently
# unable to be set through devicetree.

# Fix SPIM130 configuration in UICR, set processor id to PPR.
# Note that id of configured peripheral may change if additional peripherals are enabled in the configuration
[periph_config_2]
PROCESSOR = 13
ADDRESS = 0x5f9a5000
